# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_title', models.CharField(max_length=60)),
                ('lesson_desc', models.TextField()),
                ('lesson_id', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LessonModule',
            fields=[
                ('module_title', models.CharField(max_length=60)),
                ('module_id', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('module_lang', models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, to='lessons.Language')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.LessonModule'),
        ),
    ]
