# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodule',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonmodule',
            name='module_id',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
