# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20170122_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonmodule',
            old_name='module_id',
            new_name='module_name',
        ),
    ]
