# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20170131_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodule',
            name='id',
        ),
        migrations.AlterField(
            model_name='lessonmodule',
            name='module_name',
            field=models.CharField(db_index=True, max_length=50, serialize=False), #primary_key=True, serialize=False), ==> commented out since pk constrinats fails the migration
        ),
    ]
