# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20170131_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodule',
            name='module_num',
            field=models.PositiveSmallIntegerField(default=0) # , primary_key=True), ==> commented out since this fails the migration
        ),
    ]
