# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20170131_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodule',
            name='id',
            field=models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonmodule',
            name='module_num',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
