# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20170131_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='oppositealign',
            field=models.CharField(choices=[('rtl', 'right'), ('ltr', 'left')], default='rtl', max_length=3),
        ),
        migrations.AddField(
            model_name='language',
            name='textalign',
            field=models.CharField(choices=[('rtl', 'right'), ('ltr', 'left')], default='ltr', max_length=3),
        ),
    ]
