# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lessonvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonvideo',
            old_name='lesson',
            new_name='video_lesson',
        ),
    ]
